# Notes for 9/2

## Basic Operations

In [1]:
import math
import random

string = 'Hello, world!'
print('String: ' + string)
test = 5 + 5 # addititon
print('Addition: ' + str(test))
test -= 2 # subtraction
print('Subtraction: ' + str(test))
test *= 2 # division
print('Multiplication: ' + str(test))
test /= 2 # division
print('Division: ' + str(test))
test //= 2 # division
print('Integer division: ' + str(test))
test = test ** 2 # exponents
print('Exponents: ' + str(test))
test = math.sqrt(test) # square root
print('Square Root: ' + str(test))



String: Hello, world!
Addition: 10
Subtraction: 8
Multiplication: 16
Division: 8.0
Integer division: 4.0
Exponents: 16.0
Square Root: 4.0


## Casting

In [2]:
k = 2.33345676512321 # float

k = int(k) # chop off decimal

print(k) # full int left

x = '2' # string
print(type(x)) # type string

y = int(x) # convert to int
print(type(y)) # type int

z = str(y) # convert to string
print(type(z)) # type string

2
<class 'str'>
<class 'int'>
<class 'str'>


 ## String Operations

In [3]:
original = string # copy to another var

string = string.upper() # all to uppper case 
print('Upper: ' + string) # print upper case string

string = string.lower() # all to lower
print('Lower: ' + string) # print lower case string

string = string.strip() # remove witespace or carriage returns
print('Stripped: ' + string) # print stripped string

strLength = len(string) # length of string 
print('Length: ' + str(strLength)) # print the length


Upper: HELLO, WORLD!
Lower: hello, world!
Stripped: hello, world!
Length: 13


## Booleans

In [4]:
a = 2 # first val
b = 2.001293 # second val

boolean = (a == b) # are the values equal?
print('Result: ' + str(boolean)) # print boolean

str1 = 'test' # string one 
str2 = 'test' # string two

boolean = (str1 == str2) # are the strings equal?
print('Result: ' + str(boolean)) # print boolean

Result: False
Result: True


## Variables and Documentation

### Variable conventions
1. Naming conventions:
    - Legal characters:
    - [A-Z]
    - [a-z]
    - [0-9]
    - Underscore (_)
2. Can only start with letters and underscores, no numbers
3. No spaces
4. Cannot use a keyword 
5. Try to avoid the following
    - l (seen as 1)
    - O (seen as 0)
6. Use camel case:
    - lowerCamelCase
    - UpperCamelCase
7. Constants: UPPER
    - ex: PI- 3.14
    
### Self-Documenting Code
1. Good variable names can minimize comments
2. Name variables for the data that they store

### Whitespaces
1. Return key (enter)
    - New line: \n
    - Return: \r
    - Tab: \t
    - Space: ' '
2. Strip with the `.strip()` method for strings
    

## Data Structures (Lists) 

### Lists
**Strings are lists of** `chars`
1. Ordered
2. Mutable
    * Changes the object after use
    * Non-mutable 
3. No need for auxiliary data structures
4. Negative indexing `myList[-1]`
5. Slicing `myList[:upper]` or `myList[lower:]` or `myList[lower:upper]`
6. Append: single element
7. Extend: add multiple elements **Takes a list as input**



In [5]:
# Lists

# lists for testing
arr = ['a', 'b', 'c', 'd']
arr2 = [1, 2, 3, 4]

# indexing
print(arr[0])
print(arr[-1])

# append single element
arr.append('z')
print(arr)

# extend for multiple elements
arr.extend(arr2)
print(arr)

# mutable methods

# append
arr.append(99)
print(arr)

# extend
arr.extend(arr2)
print(arr)

# reverse
arr2.reverse()
print(arr2)

# remove first instance of element
arr.remove(99)
print(arr)

# sort the list (quicksort?)
arr2.sort()
print(arr2)

# Non-mutating

# count
count = arr.count(4)
print('Count: ' + str(count))

# index of the first occurence
index = arr.index('a')
print('Index: ' + str(index))

a
d
['a', 'b', 'c', 'd', 'z']
['a', 'b', 'c', 'd', 'z', 1, 2, 3, 4]
['a', 'b', 'c', 'd', 'z', 1, 2, 3, 4, 99]
['a', 'b', 'c', 'd', 'z', 1, 2, 3, 4, 99, 1, 2, 3, 4]
[4, 3, 2, 1]
['a', 'b', 'c', 'd', 'z', 1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4]
Count: 2
Index: 0


### Tuples

1. Immutable: once it is constructed, it cannot be changed  
    * Date/Time
    * Weekdays
    * Fixed data    
2. Advantages: 
    * Faster than lists
    * Write protected

In [6]:
listEx = [3, 64.2, 'some list'] # lists have brackets
print(type(listEx))

tupleEx = (3, 64.2, 'some list') # tuples have parentheses
print(type(tupleEx))

setEx = {3, 64.2, 'some list'} # sets have braces
print(type(setEx))

tup = tuple() # empty tuple

print(type(tup))



<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'tuple'>


### Sets

1. Distinct: no two identical elements
2. Unordered: don't index the same way lists do
3. Advantages:
    * stored once, no duplicates  
4. Disadvantage: no sense of ordering

In [7]:
sets = set() # empty set

sets.add(1)
sets.add(2)
sets.add(2)

print(sets) # print the set

sets = set(arr) # arr to sets
print(sets)

for i in range(10):
    arr.append(i + 1)

sets = set(arr) # list in set
    
print(5 in sets)

print(22 in sets)

{1, 2}
{1, 'a', 2, 3, 4, 'd', 'b', 'c', 'z'}
True
False


### Dictionaries

1. Key:value pair
2. Hash maps
3. Distinct keys
4. Advantages:
    * Mutabe
    * Unordered
    * Keys are distinct, values can be the same

In [8]:
dictionary = {} # empty dictionary

dictionary[1] = 'test' # add value
dictionary[2] = [1, 2, 3, 4]

print(dictionary) # print whole dictionary

print(dictionary[2]) # print single element

print(dictionary.keys()) # print the keys

print(dictionary.values()) # print the values

print(dictionary.items()) # print the items as tuples



{1: 'test', 2: [1, 2, 3, 4]}
[1, 2, 3, 4]
dict_keys([1, 2])
dict_values(['test', [1, 2, 3, 4]])
dict_items([(1, 'test'), (2, [1, 2, 3, 4])])


## Aliasing

1. Same data is in both locations
2. Data is not copied to the other variable

In [9]:
alias = dictionary

print(dictionary)
print(alias)

alias['Cole'] = 'hidden'
print(dictionary)
print(alias)

print(alias is dictionary)

{1: 'test', 2: [1, 2, 3, 4]}
{1: 'test', 2: [1, 2, 3, 4]}
{1: 'test', 2: [1, 2, 3, 4], 'Cole': 'hidden'}
{1: 'test', 2: [1, 2, 3, 4], 'Cole': 'hidden'}
True


## Iteration

1. Why: machines that repeat tasks
2. For loop: `for i in range(lower, upper, step):` or `for item in list:`
3. Indentation is key for loops and functions

In [10]:
ages = []

for i in range(8):
    ages.append(random.randint(0,120))
    
print(ages)

sumOfAges = 0 

for i in range(len(ages)):
    sumOfAges += ages[1]

print('Sum: ' + str(sumOfAges))

avg = sumOfAges / len(ages)
print('Average Age: ' + str(avg))


[10, 53, 96, 88, 92, 49, 15, 92]
Sum: 424
Average Age: 53.0


4. While loop `while <condition>:`

In [11]:
it = 10

while it < 15:
    print(it)
    it += 1

10
11
12
13
14


## String formatting

In [12]:
txt = 'My name is {name}, I am {age}'.format(name = 'Patrick', age = 21) # variables
print(txt)

txt = 'My name is {0}, I am {1}'.format('Patrick', 21) # indices
print(txt)

txt = 'My name is {}, I am {}'.format('Patrick', 21) # first, second
print(txt)

My name is Patrick, I am 21
My name is Patrick, I am 21
My name is Patrick, I am 21


## Advanced Data Structures

1. For loops: `for i in range(lower, upper, step): or for item in list:`
2. While loop `while <condition>:`

In [13]:
num = 839
count = 0
while num > 0:
    num = num // 10
    count += 1
    
print('The number of digits is: ' + str(count))


The number of digits is: 3


## Special Iteration

1. `range(lower, upper, step)`
2. 

In [14]:
for i in range(10):
    print (i, end = " ")

print()

for i in range(5, 10):
    print (i, end = " ")

print()

for i in range(0, 50, 5):
    print (i, end = " ")

print()

for i in range(50, 0, -5):
    print (i, end = " ")

0 1 2 3 4 5 6 7 8 9 
5 6 7 8 9 
0 5 10 15 20 25 30 35 40 45 
50 45 40 35 30 25 20 15 10 5 

## List Comprehension

1. One liners for lists and for loops

In [15]:
squares = []

for i in range(10):
    squares.append(i ** 2)
    
print(squares)

squares = [i ** 2 for i in range(10)]
print(squares)

new_count = [10 + element for element in squares]
print (new_count)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[10, 11, 14, 19, 26, 35, 46, 59, 74, 91]


## Conditionals

### `if` Statements
1. `if`: `if <condition>:`
2. `elif`: `elif <condition>:`
3. `else`: `else:`

In [16]:
arr = [1, 2, 3, 4, 99, 2, 44, 100]
maxVal = 0

for i in range(len(arr)):
    if arr[i] > maxVal:
        maxVal = arr[i]
print('Max: ' + str(maxVal))


letter = ''

tests = {'Jen': 82, 'Shannon': 75, 'Natasha': 94, 'Benjamin': 48}

for student, grade in tests.items():
    
    if grade >= 90:
        letter = 'A'
        
    elif grade >= 80: 
        letter = 'B'
    
    elif grade >= 70:
        letter = 'C'
        
    elif grade >= 60:
        letter = 'D'
    
    else: 
        letter = 'F'
    
    print(student, letter)

Max: 100
Jen B
Shannon C
Natasha A
Benjamin F


## Boolean Logic

1. `and` truth table:

X   | Y  | Result
:-: |:-: | :----:
0   | 0  | `False` 
0   | 1  | `False`
1   | 0  | `False`
1   | 1  | `True`

2. `or` truth table:

X   | Y  | Result
:-: |:-: | :----:
0   | 0  | `False` 
0   | 1  | `True`
1   | 0  | `True`
1   | 1  | `True`

3. `not` truth table:

X   | Result
:-: | :----:
0   | `True`
1   | `False`

4. `in`
5. `is`

In [35]:
x = [51, 65, 56, 19, 11, 49, 81, 59, 45, 73]
maxVal = 81
secondMax = 0

length = len(x)
it = 0 

while it < length:
    if secondMax < x[it] and x[it] < maxVal:
        secondMax = x[it]
    it += 1
print(str(secondMax) + '\n')

numbers = [i for i in range (1, 11)]
print(numbers)

for num in range(len(numbers)):
    if numbers[num] % 2 == 0:
        print(str(numbers[num]) + ' is even')
        
numbers = [i for i in range(10)]

if(13 not in numbers):
    print('\n13 is not in numbers')
    
# print(numbers)

noh = 25
noa = 12

attendance = noa / noh
medicalDoc = True

if attendance < 0.65:
    if medicalDoc:
        print('You are allowed to take the exam!')
    else:
        print('You are not able to take the exam!')
    
else:
    print('You are allowed to take the exam!')

73

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
2 is even
4 is even
6 is even
8 is even
10 is even

13 is not in numbers
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
You are allowed to take the exam!


## Error Handling

1. Common Errors:
    - `Type`
    - `Key`
    - `Index`
    - `Name`
2. Exception: raised when errors occur, solved by catching the error with `try` and `except`
3. `try` and `except`

In [25]:
#print(3/'xy') # illegal math operation

#print(j) # example of name error

#print('Debug') # should be executed when made available

try:
    
    print(z)
    
except:
    
    print('Error!')

print('Debug')

#print(10/0) # Zero division

# Function example for division


def divide(x, y):
    
    quotient = 0
    
    try:
        quotient = x / y
    
    except ZeroDivisionError:
        quotient = 'Error, Zero division!'
    
    return quotient

    
returnVal = divide(10, 0)

print('Result: ' + str(returnVal))


import random 
num = random.randint(0,1)

try:
    pass # keyword to skip over

except (NameError, ValueError):
    print('Error present!')


num = random.randint(0,1)

try:
    
    if num == 1:
        raise NameError('Happens when there is no variable defined')
        
    else:
        raise ValueError('Happens when you multiply by a string')

except (NameError, ValueError):
    print('Error present!')


print(num)

num = random.randint(0,1)

try:
    
    if num == 1:
        raise NameError('Happens when there is no variable defined')
        
except (NameError, ValueError):
    print('Error present!')

else:
    print('No errors occurred!')

print(num)


num = random.randint(0,1)

try:
    
    if num == 1:
        raise NameError('Happens when there is no variable defined')
        
    else:
        raise ValueError('Happens when you multiply by a string')

except (NameError, ValueError):
    print('Error present!')

else:
    print('No errors occurred!')
    
finally: 
    print('Always printed')

print(num)

num = random.randint(0,1)

try:
    
    if num == 1:
        raise NameError('Happens when there is no variable defined')
        
    else:
        raise Exception('Happens when you multiply by a string')

except:
    print('Error present!')

else:
    print('No errors occurred!')
    
finally: 
    print('Always printed')

print(num)

Error!
Debug
Result: Error, Zero division!
Error present!
0
Error present!
1
Error present!
Always printed
1


## Functions

### Function definitions

1. Blocks of code and scopes of code blocks
2. Defining functions:
    - Name
    - Arguments
    - Return value

```
def foo(param1, param2):
       <Some code>
       return value
```

3. Compartmentalize one thing and do it well
4. Methods are in classes
5. Functions are not in classes

In [1]:
def ourFunction():
    pass

ourFunction()

### Function Arguments (parameters)

1. As many args as you want, separated by comma
2. Provide the same number of arguments for the function in the function call

```
def fun1(one):
    <some code>    
```

Sample call: `fun1(5) # works`

Sample call: `fun1(5, 55) # error`

4. Default Arguments:
    - Positional requirements are required

In [16]:
def oneArg(one):
    print(one)
    
def twoArgs(one, two):
    print(one, two)

def threeArgs(one, two, three):
    print(one, two, three)
    
oneArg(5) # works

# oneArg(5, 55) # fails: too many params

twoArgs(5, 5) # works

# twoArgs(5, 5, 5) # fails: too many params

def funOne(param, default = 10):
    print(param, default)
    
funOne('test') # works

funOne('test', default = 999) # works

# funOne() # no params does not work

def games(user, lib):
    
    print('User {} owns: '.format(user))
    
    for game in lib:
        print('\t' + game)
        
library = ['Among Us', 'NBA 2k']

user = 'Patrick'

games(user, library)

def identity(arg):
    return arg


returnVal = identity('test')

print(returnVal)


        

5
5 5
test 10
test 999
User Patrick owns: 
	Among Us
	NBA 2k
test


### Return Values

1. `return` statement returns a value
2. Optional statement in a function
3. Multiple values can be returned
    - Returned as tuples
4. Can return dictionaries

In [4]:
def identity(arg):
    return arg


returnVal = identity('test')

print(returnVal)

def explodeString(string):
    chars = []
    for i in range(len(string)):
        chars.append(string[i])
    return chars

words = 'Onetwothree'

result = explodeString(words)

print(result)

def listToTuples(inlist):
    return 10, inlist

lst = [1, 2, 3]

print(listToTuples(lst))

def listToDictionary(inList):
    zero = inList[0]
    one = inList[1]
    two = inList[2]
    
    return {'1': zero, '2': one, '3': two}

print(listToDictionary(lst))



test
['O', 'n', 'e', 't', 'w', 'o', 't', 'h', 'r', 'e', 'e']
(10, [1, 2, 3])
{'1': 1, '2': 2, '3': 3}


### Keyword Arguments
1. Set the parameters equal to the variable
2. Order does not matter as long as the values are assigned correctly
3. Positional are always before default arguments

In [12]:
def petName(name1, name2):
    print('Pet 1:', name1)
    print('Pet 2:', name2)
    
pet1 = 'King'
pet2 = 'Bailey'

petName(pet1, pet2)

petName(name1 = pet1, name2 = pet2)

petName(name2 = pet2, name1 = pet1)

def posDef(x, y = 10):
    return x + (2 * y)

z = posDef(x = 10, y = 20)
print(z)

# define a function that takes a list and returns the unique elements of the first list

def unique_list(lst):
    
    unique = {}
    length = len(lst)
    
    for key in lst:
        unique[key] = 0
        
    return list(unique.keys())

lst = [1,1,1,2,2,2,2,3,4]

result = uniqueList(lst)
print(result)
    

Pet 1: King
Pet 2: Bailey
Pet 1: King
Pet 2: Bailey
Pet 1: King
Pet 2: Bailey
50
[1, 2, 3, 4]


## Function review
1. Palindrome function

In [8]:
def isPalindrome(string):
    
    left = 0
    right = len(string) - 1
    
    while right >= left:
        if string[left] != string[right]:
            return False
        
        left += 1
        right -= 1
        
    return True

print(isPalindrome('radar'))    

True


## Libraries
1. Import statement: `import library`
2. How to import the library: `import numpy as np`
3. Levels:
    - Built in functions: `len()`, `print()`, `max()`, `min()`
    - Default libraries: 
        - `random`: random numbers
        - `os`: Operating System
        - `re`: RegEx
        - `datetime`: date and time
        - `math`: math library
        - `xml`: parsing xml files
    - Python Package Index (manual):
        - `pip3 install [package]`
    

In [11]:
import random as r

print(r.randint(0, 1))

1


## Numpy
1. Numperical Python
2. One of the most popular packages
3. Core: ndarray
    - n-dimensional array
    - matrices

In [12]:
matrix = [[1,2,3], [4,5,6], [7,8,9]]

print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [18]:
import numpy as np

matrix = [[1,2,3], [4,5,6], [7,8,9]]

arr = np.array(matrix)

print(arr)
print(type(arr))

print(arr[0])
print(arr[2][2]) # [row] [column]
print(arr[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[1 2 3]
9
9


## More Numpy
1. `ndarray`
2. Submodules:
    - `ndarray`
    - `sin`
    - `cos`
    - `log`
    - `exp`
    - `max`
    - `min`
3. Fourier Transform
    - `fft`: infinite sum of sine and cosine waves
4. Linear Algebra:
    - `linalg.norm`
    - `linalg.svd`
    - `linalg.det`
5. Random Numbers:
    - `random`
6. Testing:
    - `testing.assert_allclose()`
7. Vectorized Arithmetic:
    - Broadcasting: vectorized operations with different shapes
    - Compatible same rows and columns
    - One Dimensional array

In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print('Min:', np.min(arr))
print('Cos of first element: {:.2f}'.format(np.cos(arr[0])))

print(np.random.randint(10)) # non-inclusive end point like range f(x)

arr = np.array([1, 2])
brr = np.array([3, 4])



print(np.testing.assert_allclose(arr, arr))

#print(np.testing.assert_allclose(arr, brr))

our_list= [5, 10, 15, 20, 25]
our_list = [x ** 2 for x in our_list]
print(our_list)

our_list = [5, 10, 15, 20, 25]

nd = np.array(our_list)

nd = nd ** 2

print(nd)

new_list = [10, 21, 30, 42, 54]
nd = np.array(new_list)

nd = nd // 5

print(nd)

import numpy as np
import numpy.linalg as nla

vector = [4.0, 15.0, 6.0, 2.0]

npVector = np.array(vector)
magnitude = nla.norm(npVector)

npVector /= magnitude

print(magnitude)


Min: 1
Cos of first element: 0.54
5
None
[25, 100, 225, 400, 625]
[ 25 100 225 400 625]
[ 2  4  6  8 10]
16.76305461424021


## Midterm
1. Exam will be on Mimir
2. Open note
3. No collaboration
4. Multiple Submissions
5. 11:30 - ? (extra hour?)
6. Review Wednesday

In [8]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

z = x + y

print(z)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A @ B

print(C)

print(C.shape)

def multiplyMatrices(A, B):
    
    C = np.zeros((A.shape[0], B.shape[1]))
    
    for row in range(len(A)):      
        for col in range(len(B[0])):
            for k in range(len(B)):
                C[row][col] += A[row][k] * B[k][col]
    
    return C

one = np.array([[1,2,3,4], [5,6,7,8]])
two = np.array([[1,2], [1,2]])

print(one)
print(two)

# print(multiplyMatrices(one, two))


X = np.random.random([100, 100])
Y = np.random.random([100, 100])

#%timeit multiplyMatrices(X, Y)
#%timeit X @ Y



# normal list
lst = [1, 2, 3, 4]

print(lst)
print(lst[1:3])
print(lst[2:])
print(lst[:-1])

# numpy equivalent
lst = np.array(lst)

print(lst)
print(lst[1:3])
print(lst[2:])
print(lst[:-1])




[5 7 9]
[[19 22]
 [43 50]]
(2, 2)
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [1 2]]
[1, 2, 3, 4]
[2, 3]
[3, 4]
[1, 2, 3]
[1 2 3 4]
[2 3]
[3 4]
[1 2 3]


## Numpy Array Broadcasting
1. Sliceing works for printing rows and columns
2. Advanced Slicing:
    - `[start:stop]`
    - `[start:stop:end]`
3. Broadcasting: vectorized operations with different shapes
    - Compatible same rows and columns
    - One Dimensional array

In [1]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(x)

print(x[:, 1])

print(x[:2, 1:])

print(x[2:, :])

print(x[:, :2])

print(x[1:2, :2])

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a)

print(a[:, 1::2])

matrix = np.arange(0,36)
matrix = matrix.reshape(6,6)

print(matrix)

print(matrix[2::2, 0::2])

video = np.empty(shape = (1280, 720, 50))
print(video.ndim)

del video

#tensor = np.empty(shape = (2, 640, 480, 360, 100))
#print(tensor.shape)

ex = np.empty(shape = (3, 5, 9))
print(ex.shape)

sliced = ex[0]
print(sliced.shape)

sliced = ex[0, 0]
print(sliced.shape)

ex = np.zeros(shape = (3, 5, 9))
print(ex)

ex = ex[0]
print(ex.shape)

x = np.array([1,2,3,4,5])

x += 10

print(x)

zeros = np.zeros(shape = (3, 4))

zeros += 1

print(zeros)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]
[[2 3]
 [5 6]]
[[7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[4 5]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  4]
 [ 6  8]
 [10 12]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[12 14 16]
 [24 26 28]]
3
(3, 5, 9)
(5, 9)
(9,)
[[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
(5, 9)
[11 12 13 14 15]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## More numpy
1. Preprocessing
    - AKA cleaning data
2. Boolean indexing (masking)
    - `and`: &
    - `or`: |

In [5]:
import numpy as np

x = np.random.standard_normal(size = (7, 4))

print(x)

mask = x < 0

print(mask)

x[mask] = 0
print(x)



[[ 0.52695565 -0.02963544  1.4328452  -2.00719192]
 [-0.3643898   0.81683406  1.93403711 -1.8244274 ]
 [ 0.6227351  -0.28187691  0.62220112  1.71825749]
 [ 2.44725776 -2.27445449  0.82949197 -0.641628  ]
 [ 1.39735632  0.29008627  0.3129043   0.85414358]
 [ 2.95312222 -1.36585731  0.80070001  1.16707487]
 [-0.32170231  0.0102576  -0.15302296 -0.3428753 ]]
[[False  True False  True]
 [ True False False  True]
 [False  True False False]
 [False  True False  True]
 [False False False False]
 [False  True False False]
 [ True False  True  True]]
[[0.52695565 0.         1.4328452  0.        ]
 [0.         0.81683406 1.93403711 0.        ]
 [0.6227351  0.         0.62220112 1.71825749]
 [2.44725776 0.         0.82949197 0.        ]
 [1.39735632 0.29008627 0.3129043  0.85414358]
 [2.95312222 0.         0.80070001 1.16707487]
 [0.         0.0102576  0.         0.        ]]


## Interacting with the File System
### Input
1. `input()` grabs user keyboard text


In [5]:
test = input('Enter your name: ')
print(type(test))

age = int(input('Enter your age: '))
print(age)


Enter your name: 5
<class 'str'>


### File I/O
1. `inFile = open('file.ext', 'r/w')`
2. Need a data structure to hold the line data
3. Need a loop to iterate over the lines

In [3]:
import numpy as np

inFile = open('alice.txt', 'r')

content = inFile.read()

print(content[:71])

inFile.close()

with open('alice.txt', 'r') as inFile:
    content = inFile.read()
    print(content[:71])

inFile = open('alice.txt', 'r')
    
data = []
lines = 0

for line in inFile:
    line = line.strip()
    print(line)
    lines += 1
    if lines == 5: 
        break
inFile.close()

inFile = open('alice.txt', 'r')
data = inFile.readlines()
print(data[0])
inFile.close()

outFile = open('out.txt', 'w')
outFile.write(str(5))
outFile.close()

Project Gutenberg's Alice's Adventures in Wonderland, by Lewis Carroll

Project Gutenberg's Alice's Adventures in Wonderland, by Lewis Carroll

Project Gutenberg's Alice's Adventures in Wonderland, by Lewis Carroll

This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
Project Gutenberg's Alice's Adventures in Wonderland, by Lewis Carroll



## More file I/O and OS library
1. OS library
2. `import os`
    - `os.getcwd()`: absolute path
    - `os.chdir('[path]')`: change directory
    - `os.listdir('[directory]')`: lists all the files
    - `os.mkdir('name')`: make directory
    - `os.rmdir('directory')`: delete a directory
    - `os.remove('file')`: removes a file
    - `os.unlink('file')`: another way to delete
    - `os.rename('old', 'new'): rename files or directories
3. `import os.path as p`
    - `exists('file')`: boolean does or not exists
    - `isdir('name')`: is it a file or directory?

In [ ]:
import os 
import os.path as p

os.chdir('/home/pmccabe/Desktop/Github Repositories/Data-Science')

print(os.getcwd()) # get current working directory 

os.chdir('DATA101') # change to the DATA101 folder

print(os.getcwd()) # get current working directory

os.listdir('.') # list all the files of the current directory

os.mkdir('test') # create a directory

print(os.listdir('.')) # list new directories

os.rmdir('test') # removes the test directory

os.mkdir('test') # create a directory

os.listdir('.') # list new directories

os.rename('test', 'test2') # rename file

print(os.listdir('.')) # list new directories

p.exists('test2')

for file in os.listdir('.'):
    if file.endswith('txt'):
        print(p.join(os.getcwd(), file))

os.rmdir('test2')

## Linear Algebra
1. Terminology
    - scalar: single number
    - vector: collection of scalars
2. Scalars:
    - magnitude 
    - direction
3. Space (vector space):
    - All possible vectors we may have
    - finite in dimension, infinite in space
    - vectors live in space
4. Systems of Equations
    - Substitution: solve for one and then calculate the other
    - Elimination: eliminate one of the variables
5. Vectors and Matrices

In [1]:
import numpy as np

one = [1, 1]
two = [0.45, 0.65]

A = np.array([one, two])

print(A)

yVector = [35, 18.55]



[[1.   1.  ]
 [0.45 0.65]]


## Statistics
1. Def: sumarize the data
2. Make predcictions on the whole population based on a sample


In [ ]:
import numpy as np
import statistics

## Misc.

In [ ]:
n = 11

for i in range(n):
    for j in range(i):
        print('*', end = '')
    print()
for l in range(n, 0, -1):
    for k in range(l):
        print('*', end = '')
    print()
    
l1 = [1, 2, 3]
l2 = [4, 5, 6]
l3 = [7, 8, 9]
test = zip(l1, l2, l3)
print(test)