# Practice Problems:

1. Create a `calc` function that takes in 3 paramaeters: operation, par1, par2

In [ ]:
def calc(operation, par1, par2 ):
    
    ops = ['+', '-', '*', '**', '/', '//', '%']
    
    operation = str(operation)
    
    if operation not in ops:
        operation = operation.lower()
    
    if operation == '+' or operation == 'add':
        return par1 + par2
    
    elif operation == '-' or operation == 'sub':
        return par1 - par2
    
    elif operation == '*' or operation == 'mul':
        return par1 * par2
    
    elif operation == '**' or operation == 'pow':
        return par1 ** par2
    
    elif operation == '/' or operation == 'div':
        return par1 / par2
    
    elif operation == '//' or operation == 'int-div':
        return par1 // par2
    
    elif operation == '%' or operation == 'mod':
        return par1 % par2
    
    else: 
        
        legalOperations = ['+ or add', '- or sub', '* or mul', '** or pow', '/ or div', '// or int-div', '% or mod']
        
        print('Function not defined or keyword has been specified! Please enter in one of the following operations as a string: \n')
        
        for op in legalOperations:
            print(op)
        
        return 'ERROR!!!'
    
calcResults = []

result = calc('add', 2, 2)
calcResults.append(result)

result = calc('+', 2, 2)
calcResults.append(result)

result = calc('sub', 2, 2)
calcResults.append(result)

result = calc('-', 2, 2)
calcResults.append(result)

result = calc('mul', 2, 2)
calcResults.append(result)

result = calc('*', 2, 2)
calcResults.append(result)

result = calc('div', 2, 2)
calcResults.append(result)

result = calc('/', 2, 2)
calcResults.append(result)

result = calc('**', 2, 2)
calcResults.append(result)

result = calc('pow', 2, 2)
calcResults.append(result)

result = calc('int-div', 2, 2)
calcResults.append(result)

result = calc('//', 2, 2)
calcResults.append(result)

result = calc('mod', 2, 2)
calcResults.append(result)

result = calc('%', 2, 2)
calcResults.append(result)

print(calcResults)

print(calc('ADD', 2, 2))

print(calc('sin', 2, 2))

In [7]:
import random
 
def foo(l1, l2, l3, l4):
    
    storage = []
    
    arr = zip(l1, l2, l3, l4)
    
    total = 0
    
    for i, j, k, l in arr:
        
        total = (i + j + k + l)
        storage.append(total)
        
    return storage

def createDict(keys, values):
    
    dictionary = {}
    
    arr = zip(keys, values)
    
    for key, value in arr:
        
        dictionary[key] = value
        
    return dictionary

def minVal(values):
    
    length = len(values)
    
    if length > 0:
        
        minimumVal = values[0]
            
        for i in range(length):
            if values[i] < minimumVal:
                minimumVal = values[i]
            
        
    return minimumVal

def main():
    
    li1 = [1, 2, 45]
    li2 = [3, 4, 42]
    li3 = [5, 6, 21]
    li4 = [7, 8, 99]
    
    var = foo(li1, li2, li3, li4)
    
    print(var)
    
    squares = ((li1[2] ** 2) + (li2[2] ** 2)) / 2
    
    print(squares)

    library = createDict(li1, li2)
    
    print(library)
    print(library.values())
    
    for key in library:
        library[key] *= 100
    
    print(library)
    
    arr = []
    
    for i in range(15):
        arr.append(random.randint(0, 100))
        #print(arr)
    
    maximum = minVal(arr)
    print(maximum)
    
main()

[16, 20, 207]
1894.5
{1: 3, 2: 4, 45: 42}
dict_values([3, 4, 42])
{1: 300, 2: 400, 45: 4200}
5


In [4]:
def inList(lst, key):
    
    if key in lst:
        return True
    else:
        return False

    

lst = {1, 5, 10, 17}

result = inList(lst, 10)

if result:
    print('The element is in the list!')

else:
    print('The element is not in the list!')

    
result = inList(lst, 42)

if result:
    print('The element is in the list!')

else:
    print('The element is not in the list!')

The element is in the list!
The element is not in the list!


In [1]:
import numpy as np

arr = np.array([1, 2])
brr = np.array([3, 4])

for i in range (len(arr)):
    print(arr[i])
    

1
2


In [1]:
import random
import numpy as np

def addLists(lst1, lst2):
    
    result = []
    
    
    if len(lst1) != len(lst2):
        return 0
    
    for i in range(len(lst1)):
        total = lst1[i] + lst2[i]
        result.append(total)
        total = 0
        
    return result

arr1 = [random.randint(0, 100) for x in range(10)]
arr2 = [random.randint(0, 100) for x in range(10)]

print(arr1)
print(arr2)

#print(arr1[::-1])

result = addLists(arr1, arr2)

print(result)

npArr = np.array(arr1)
npBrr = np.array(arr2)

res = npArr + npBrr

print(res)

matrix = np.array([[2,4,6,8], [1,3,5,7]])

print(matrix)

print(matrix[1:, :2])

[39, 29, 8, 61, 78, 35, 89, 12, 11, 28]
[13, 26, 91, 88, 9, 33, 97, 43, 79, 70]
[52, 55, 99, 149, 87, 68, 186, 55, 90, 98]
[ 52  55  99 149  87  68 186  55  90  98]
[[2 4 6 8]
 [1 3 5 7]]
[[1 3]]


## Numpy Vectors

In [2]:
import numpy as np
import random
x = [random.randint(0, 100) for i in range(15)]
y = [random.randint(0, 100) for i in range(15)]
z = [random.randint(0, 100) for i in range(15)]

npX = np.array(x)
npY = np.array(y)
npZ = np.array(z)

result = np.array([])

result = npX + npY + npZ
print(result)



[121 102 144 157 245 125 170  92 200 258 156 122 103 173 119]


## Numpy Slicing and Multi-Dimensional Arrays

In [3]:
npArr = np.arange(0, 100)
npArr = npArr.reshape(10, 10)

print(npArr) # entire npArray

print(npArr[0, 0]) # first element

print(npArr[0]) # first row only

print(npArr[:, 5]) # fifth column only

print(npArr[1:, :5]) # print everything from the second row up to the fourth column

print(npArr[0:6:2, 0:6:2]) # print the the rows and columns from 0 to the thrid, and step 2

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
0
[0 1 2 3 4 5 6 7 8 9]
[ 5 15 25 35 45 55 65 75 85 95]
[[10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]
 [60 61 62 63 64]
 [70 71 72 73 74]
 [80 81 82 83 84]
 [90 91 92 93 94]]
[[ 0  2  4]
 [20 22 24]
 [40 42 44]]


## Try and Except

In [1]:
import random

r = random.randint(0, 1000)
print(r)

try:
    
    if r > 750:
        print('Number is good!')
    else: 
        raise Exception
        
except:
    print('Bad number!')

    
dictionary = {}

for i in range(5):
    dictionary[i] = random.randint(0, 42)

print(dictionary)

keys = [0, 2, 5, 1, 7]

for key in keys:

    try: 
        if key in dictionary:
            print(dictionary[key])
        else:
            raise KeyError

    except KeyError:
        print(key, 'Key not in dictionary!')

dictionary[0] = 'Maybe this is a key?'

dictionary['key'] = 'Maybe this is a key?'

print(dictionary)
print(dictionary[0])
print(dictionary['key'])

#for key in keys:
#    print(dictionary[key])

380
Bad number!
{0: 4, 1: 1, 2: 11, 3: 34, 4: 32}
4
11
5 Key not in dictionary!
1
7 Key not in dictionary!
{0: 'Maybe this is a key?', 1: 1, 2: 11, 3: 34, 4: 32, 'key': 'Maybe this is a key?'}
Maybe this is a key?
Maybe this is a key?


## Boolean Masks

In [24]:
import numpy as np
import random as r
x = [r.randint(0, 100) for i in range(15)]

npArr = np.array(x)

print(npArr)

mask = npArr > 50

print(mask)

print(npArr[mask])

mask = (npArr > 50) & (npArr < 75)

print(mask)

print(npArr[mask])

[74 47 19 97 96  7 99 36 35 96 79 23 16 40 92]
[ True False False  True  True False  True False False  True  True False
 False False  True]
[74 97 96 99 96 79 92]
[ True False False False False False False False False False False False
 False False False]
[74]


## Logical Equivalents

In [23]:
op1 = True
op2 = False 

result = op1 and op2

print(result)

op1 = True
op2 = False 

result = op1 or op2

print(result)

op1 = False
op2 = False 

result = not(op1 or op2) # same as result = op1 and op2

print(result)

op1 = False
op2 = False 

result = not(op1 and op2) # result = op1 or op2

print(result)

False
True
True
