# Practice Problems:

1. Create a `calc` function that takes in 3 paramaeters: operation, par1, par2

In [ ]:
def calc(operation, par1, par2 ):
    
    ops = ['+', '-', '*', '**', '/', '//', '%']
    
    operation = str(operation)
    
    if operation not in ops:
        operation = operation.lower()
    
    if operation == '+' or operation == 'add':
        return par1 + par2
    
    elif operation == '-' or operation == 'sub':
        return par1 - par2
    
    elif operation == '*' or operation == 'mul':
        return par1 * par2
    
    elif operation == '**' or operation == 'pow':
        return par1 ** par2
    
    elif operation == '/' or operation == 'div':
        return par1 / par2
    
    elif operation == '//' or operation == 'int-div':
        return par1 // par2
    
    elif operation == '%' or operation == 'mod':
        return par1 % par2
    
    else: 
        
        legalOperations = ['+ or add', '- or sub', '* or mul', '** or pow', '/ or div', '// or int-div', '% or mod']
        
        print('Function not defined or keyword has been specified! Please enter in one of the following operations as a string: \n')
        
        for op in legalOperations:
            print(op)
        
        return 'ERROR!!!'
    
calcResults = []

result = calc('add', 2, 2)
calcResults.append(result)

result = calc('+', 2, 2)
calcResults.append(result)

result = calc('sub', 2, 2)
calcResults.append(result)

result = calc('-', 2, 2)
calcResults.append(result)

result = calc('mul', 2, 2)
calcResults.append(result)

result = calc('*', 2, 2)
calcResults.append(result)

result = calc('div', 2, 2)
calcResults.append(result)

result = calc('/', 2, 2)
calcResults.append(result)

result = calc('**', 2, 2)
calcResults.append(result)

result = calc('pow', 2, 2)
calcResults.append(result)

result = calc('int-div', 2, 2)
calcResults.append(result)

result = calc('//', 2, 2)
calcResults.append(result)

result = calc('mod', 2, 2)
calcResults.append(result)

result = calc('%', 2, 2)
calcResults.append(result)

print(calcResults)

print(calc('ADD', 2, 2))

print(calc('sin', 2, 2))

In [7]:
import random
 
def foo(l1, l2, l3, l4):
    
    storage = []
    
    arr = zip(l1, l2, l3, l4)
    
    total = 0
    
    for i, j, k, l in arr:
        
        total = (i + j + k + l)
        storage.append(total)
        
    return storage

def createDict(keys, values):
    
    dictionary = {}
    
    arr = zip(keys, values)
    
    for key, value in arr:
        
        dictionary[key] = value
        
    return dictionary

def minVal(values):
    
    length = len(values)
    
    if length > 0:
        
        minimumVal = values[0]
            
        for i in range(length):
            if values[i] < minimumVal:
                minimumVal = values[i]
            
        
    return minimumVal

def main():
    
    li1 = [1, 2, 45]
    li2 = [3, 4, 42]
    li3 = [5, 6, 21]
    li4 = [7, 8, 99]
    
    var = foo(li1, li2, li3, li4)
    
    print(var)
    
    squares = ((li1[2] ** 2) + (li2[2] ** 2)) / 2
    
    print(squares)

    library = createDict(li1, li2)
    
    print(library)
    print(library.values())
    
    for key in library:
        library[key] *= 100
    
    print(library)
    
    arr = []
    
    for i in range(15):
        arr.append(random.randint(0, 100))
        #print(arr)
    
    maximum = minVal(arr)
    print(maximum)
    
main()

[16, 20, 207]
1894.5
{1: 3, 2: 4, 45: 42}
dict_values([3, 4, 42])
{1: 300, 2: 400, 45: 4200}
5


In [4]:
def inList(lst, key):
    
    if key in lst:
        return True
    else:
        return False

    

lst = {1, 5, 10, 17}

result = inList(lst, 10)

if result:
    print('The element is in the list!')

else:
    print('The element is not in the list!')

    
result = inList(lst, 42)

if result:
    print('The element is in the list!')

else:
    print('The element is not in the list!')

The element is in the list!
The element is not in the list!


In [1]:
import numpy as np

arr = np.array([1, 2])
brr = np.array([3, 4])

for i in range (len(arr)):
    print(arr[i])
    

1
2


In [20]:
import random
import numpy as np

def addLists(lst1, lst2):
    
    result = []
    
    
    if len(lst1) != len(lst2):
        return 0
    
    for i in range(len(lst1)):
        total = lst1[i] + lst2[i]
        result.append(total)
        total = 0
        
    return result

arr1 = [random.randint(0, 100) for x in range(10)]
arr2 = [random.randint(0, 100) for x in range(10)]

print(arr1)
print(arr2)

#print(arr1[::-1])

result = addLists(arr1, arr2)

#print(result)

npArr = np.array(arr1)
npBrr = np.array(arr2)

res = npArr + npBrr

print(res)

matrix = np.array([[2,4,6,8], [1,3,5,7]])

print(matrix)

print(matrix[1:, :2])

[24, 46, 8, 33, 51, 9, 51, 92, 78, 78]
[40, 8, 91, 31, 83, 92, 51, 31, 80, 18]
[ 64  54  99  64 134 101 102 123 158  96]
[[2 4 6 8]
 [1 3 5 7]]
[[1 3]]


## Numpy Vectors

In [16]:
import numpy as np
import random

x = [random.randint(0, 100) for i in range(15)]
y = [random.randint(0, 100) for i in range(15)]
z = [random.randint(0, 100) for i in range(15)]

print(x)
print(y)
print(z)

npX = np.array(x)
npY = np.array(y)
npZ = np.array(z)

result = np.array([])

result = npX + npY + npZ
print(result)


def div(npA, npB):
    
    return npA / npB

check = div(npX, npY)
print(check)


[73, 81, 94, 27, 14, 98, 13, 8, 33, 100, 5, 90, 50, 47, 52]
[83, 71, 32, 66, 88, 34, 24, 12, 67, 31, 73, 55, 51, 12, 65]
[34, 64, 90, 93, 13, 43, 74, 90, 80, 37, 26, 31, 83, 65, 3]
[190 216 216 186 115 175 111 110 180 168 104 176 184 124 120]
[0.87951807 1.14084507 2.9375     0.40909091 0.15909091 2.88235294
 0.54166667 0.66666667 0.49253731 3.22580645 0.06849315 1.63636364
 0.98039216 3.91666667 0.8       ]


## Numpy Slicing and Multi-Dimensional Arrays

In [32]:
npArr = np.arange(0, 100)
print(npArr)

npArr = npArr.reshape(10, 10)

print(npArr) # entire npArray

print(npArr[0, 0]) # first element

print(npArr[0]) # first row only

print(npArr[:, 5]) # fifth column only

print(npArr[1:, :5]) # print everything from the second row up to the fourth column

print(npArr[0:6:2, 0:6:2]) # print the the rows and columns from 0 to the thrid, and step 2

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
0
[0 1 2 3 4 5 6 7 8 9]
[ 5 15 25 35 45 55 65 75 85 95]
[[10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]
 [60 61 62 63 64]
 [70 71 72 73 74]
 [80 81 82 83 84]
 [90 91 92 93 94]]
[[ 0  2  4]
 [20 22 24]
 [40 42 44]]


## Try and Except

In [35]:
import random

r = random.randint(0, 1000)
print(r)

try:
    
    if r > 750:
        print('Number is good!')
    else: 
        raise Exception
        
except:
    print('Bad number!')

    
dictionary = {}

for i in range(5):
    dictionary[i] = random.randint(0, 42)

print(dictionary)

keys = [0, 2, 5, 1, 7]

for key in keys:

    try: 
        if key in dictionary:
            print(dictionary[key])
        else:
            raise KeyError

    except KeyError:
        print(key, 'Key not in dictionary!')

dictionary[0] = 'Maybe this is a key?'

dictionary['key'] = 'Maybe this is a key?'

print(dictionary)
print(dictionary[0])
print(dictionary['key'])

#for key in keys:
#    print(dictionary[key])

700
Bad number!
{0: 21, 1: 17, 2: 41, 3: 24, 4: 42}
21
41
5 Key not in dictionary!
17
7 Key not in dictionary!
{0: 'Maybe this is a key?', 1: 17, 2: 41, 3: 24, 4: 42, 'key': 'Maybe this is a key?'}
Maybe this is a key?
Maybe this is a key?


## Developing Test Cases

In [13]:

def add(x, y):
    
    ### START SOLUTION
    
    print(type(x))
    print(type(y))
    
    #x = str(x)
    #y = str(y)
    
    print(type(x))
    print(type(y))
    
    total = x + y
    
    ### END SOLUTION
    
    return total

var1 = 1
var2 = 2

result = add(var1, var2)
print('Result: ' + str(result))

result = add(3, 4)
print('Result: ' + str(result))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
Result: 3
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
Result: 7


## Loops

In [36]:
# starter list 
lst = []

# range

for i in range(15): # generic range function with just the upper bound
    lst.append(i)
    
print(lst)

for i in range(0, 15):
    print(lst[i], end = ' ')
print()

# shorthand (condensed)

for element in lst:
    print(element, end = " ")
print()

for element in lst:
    print(lst[element], end = " ")
print()
# list comprehension

x = [i for i in range(0, 15 , 1)]

k = [1, 15, 22, 3, 42]
d = {}

for key in k:
    d[key] = 0
print(d)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 
{1: 0, 15: 0, 22: 0, 3: 0, 42: 0}


## Data Structures

In [57]:
# lists: methods to know

x = [1,2,3,4]
y = [5,6,7,8,9]

y.append(9) # simple append
print(y)

x.extend(y) # appends the elements of y into x
print(x)

x.remove(9) # removes 9 from x
print(x)

x.reverse() # reverses the list
print(x)

x.sort() # quicksort of x
print(x)

print(x.count(1))

print(x.index(1))

# sets

sets = set() # create set

# add elements to the set
sets.add(1) 
sets.add(1)
sets.add(2)
sets.add(3)

print(sets)

# tuples

# create tuple
tup = (1,2,3,3)
print(tup)

#cast list to tuple
tupX = tuple(x)
print(tupX)

# dictionaries
dictionary = {42: 'test'}

dictionary[1] = 'some text'
dictionary[2] = 5
dictionary[3] = 7.2


print(dictionary)

print(dictionary.keys())

print(dictionary.values())

print(dictionary.items())

[5, 6, 7, 8, 9, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
1
0
{1, 2, 3}
(1, 2, 3, 3)
(1, 2, 3, 4, 5, 6, 7, 8, 9)
{42: 'test', 1: 'some text', 2: 5, 3: 7.2}
dict_keys([42, 1, 2, 3])
dict_values(['test', 'some text', 5, 7.2])
dict_items([(42, 'test'), (1, 'some text'), (2, 5), (3, 7.2)])
